[package]
name = "ec2-instance-metadata"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "ec2im"
path = "src/main.rs"

[dependencies]
chrono = "0.4.42"
clap = { version = "4.5.53", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
